helloworld:
   path: /etc/opt/srlinux/appmgr/helloworld_agent/
   launch-command: /etc/opt/srlinux/appmgr/helloworld_agent/helloworld.sh
   search-command:
       /bin/bash /etc/opt/srlinux/appmgr/helloworld_agent/helloworld.sh
   wait-for-config: No
   failure-threshold: 10
   failure-action: wait=forever
   restricted-operations: ['kill','quit','restart','reload']
   author: 'SR Linux course'
   version-command:
       /etc/opt/srlinux/appmgr/helloworld_agent/helloworld_version.sh
   yang-modules:
       names:
           - "helloworld"
       source-directories:
           - "/etc/opt/srlinux/appmgr/helloworld_agent/yang/"

